version: 2
jobs:
  build:
    docker:
      - image: golang:1.11
      - image: rabbitmq:3
        environment:
          RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
          RABBITMQ_DEFAULT_USER: rabbitmq
          RABBITMQ_DEFAULT_PASS: rabbitmq
          RABBITMQ_DEFAULT_VHOST: /
      - image: postgres
        environment:
          POSTGRES_PASSWORD: rhinof
          POSTGRES_USER: rhinof
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for rabbitmq
          command: dockerize -wait tcp://localhost:5672 -timeout 1m
      - run: go get -v -t -d ./...
      - run: go test -timeout 300s -v ./...
